force-app/main/default/objects/JobApplication__c/JobApplication__c.object-meta.xml
<CustomObject>
    <description>Object responsible to track Job Applications</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplication__c/fields/AppliedDate__c.field-meta.xml
<CustomField>
    <fullName>AppliedDate__c</fullName>
    <description>Apply job date</description>
    <label>Applied Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Company name</description>
    <label>Company</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Role name</description>
    <label>Role</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobApplication__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Job status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interview</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobAppController.cls
/**
 * @author bruno.moreira
 */
public with sharing class JobAppController {
    
    @AuraEnabled(cacheable=true)
    public static List<JobApplication__c> getApplications() {

        return [

            SELECT Id, Company__c, Role__c, Status__c, AppliedDate__c FROM JobApplication__c ORDER BY AppliedDate__c ASC LIMIT 200

        ];

    }

    @AuraEnabled
    public static void updateApplicationStatus(Id recordId, String newStatus) {

        if (recordId == null || String.isBlank(newStatus)) {

            throw new AuraHandledException('recordId and newStatus are required!');

        }

        JobApplication__c jobApplication = [ SELECT Id, Status__c FROM JobApplication__c WHERE Id =: recordId LIMIT 1 ];

        jobApplication.Status__c = newStatus;

        update jobApplication;

        System.debug('Job Applications: ' + jobApplication);

    }

}